# build environment
FROM node:16.15-alpine

WORKDIR /app
RUN mkdir /app/images

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./

RUN npm run build

CMD ["npm", "start"]
